set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction horizontal  -start_at 0.690 -nets VDD -layer M8 -width 0.320 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 53.870 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 54.670 -nets VDD -layer M8 -width 0.320 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 53.870 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 53.350 -nets VDD -layer M9 -width 1.040 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 54.830 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 1.050 -nets VDD -layer M9 -width 1.040 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 54.830 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 1.200 -nets VSS -layer M8 -width 0.320 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 52.300 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 54.160 -nets VSS -layer M8 -width 0.320 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 52.300 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 51.780 -nets VSS -layer M9 -width 1.040 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 54.320 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 2.620 -nets VSS -layer M9 -width 1.040 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 54.320 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
# Starting to commit metal8 straps for net VDD
create_power_straps  -direction horizontal  -start_at 3.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 53.870 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 5.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 53.870 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 7.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 53.870 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 9.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 53.870 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 11.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 53.870 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 13.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 53.870 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 15.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 53.870 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 17.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 53.870 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 19.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 53.870 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 21.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 53.870 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 23.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 53.870 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 25.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 53.870 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 27.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 53.870 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 29.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 53.870 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 31.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 53.870 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 33.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 53.870 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 35.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 53.870 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 37.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 53.870 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 39.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 53.870 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 41.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 53.870 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 43.320 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 53.870 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 45.820 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 53.870 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 47.820 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 53.870 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 49.820 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 53.870 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 51.820 -nets VDD  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 53.870 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal8 straps for net VSS
create_power_straps  -direction horizontal  -start_at 3.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 52.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 5.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 52.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 7.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 52.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 9.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 52.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 11.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 52.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 13.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 52.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 15.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 52.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 17.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 52.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 19.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 52.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 21.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 52.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 23.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 52.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 25.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 52.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 27.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 52.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 29.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 52.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 31.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 52.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 33.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 52.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 35.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 52.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 37.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 52.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 39.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 52.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 41.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 52.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 43.680 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 52.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 46.180 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 52.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 48.180 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 52.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 50.180 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 52.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 52.180 -nets VSS  -layer M8 -width 0.160 -pitch_within_group 2.020 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 52.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VDD
create_power_straps  -direction vertical  -start_at 5.450 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 2.830 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 54.830 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 8.250 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 2.830 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 54.830 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 11.060 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 2.830 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 54.830 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 13.860 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 2.830 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 54.830 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 16.670 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 2.830 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 54.830 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 19.470 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 2.830 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 54.830 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 22.280 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 2.830 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 54.830 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 25.080 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 2.830 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 54.830 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 27.890 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 2.830 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 54.830 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 30.690 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 2.830 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 54.830 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 33.500 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 2.830 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 54.830 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 36.300 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 2.830 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 54.830 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 39.110 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 2.830 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 54.830 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 41.910 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 2.830 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 54.830 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 44.720 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 2.830 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 54.830 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 47.520 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 2.830 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 54.830 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VSS
create_power_straps  -direction vertical  -start_at 6.500 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 2.830 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 54.320 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 9.310 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 2.830 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 54.320 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 12.110 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 2.830 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 54.320 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 14.920 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 2.830 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 54.320 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 17.720 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 2.830 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 54.320 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 20.530 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 2.830 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 54.320 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 23.330 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 2.830 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 54.320 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 26.140 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 2.830 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 54.320 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 28.940 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 2.830 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 54.320 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 31.750 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 2.830 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 54.320 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 34.550 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 2.830 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 54.320 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 37.360 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 2.830 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 54.320 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 40.160 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 2.830 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 54.320 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 42.970 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 2.830 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 54.320 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 45.770 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 2.830 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 54.320 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 48.580 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 2.830 -start_low_ends coordinate  -start_low_ends_coordinate 1.040 -start_high_ends coordinate  -start_high_ends_coordinate 54.320 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
